services:
  backend:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - APP_ENV=PROD
      - DATABASE_URI=postgres://postgres:mysecretpassword@db:5432/newspaper_users
      - SECRETWORDJWT=ba72f4da0bf07a8483781f2a6d39d933ac010720
      - REDIS_URI=redis:6379
      - REDIS_DATABASE=1
      - SECOND_DELAY=2
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:latest 
    ports: 
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: newspaper_users
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d newspaper_users"]
      interval: 5s
      retries: 10
    volumes:
      - pgdata2:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

volumes:
  pgdata2:
  redisdata:
