basePath: /
definitions:
  dto.ErrorDTO:
    properties:
      error:
        type: string
    type: object
host: localhost:port
info:
  contact: {}
  description: api for a [name] project
  title: Backend Portfolio API
  version: "1.0"
paths: {}
swagger: "2.0"
