basePath: /
definitions:
  dto.CreateUserDTO:
    properties:
      email:
        maxLength: 100
        type: string
      fullname:
        maxLength: 100
        type: string
      password:
        type: string
      username:
        maxLength: 50
        type: string
    required:
    - email
    - fullname
    - password
    - username
    type: object
  dto.ErrorDTO:
    properties:
      error:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: api for a user services for a newspaper
  title: Backend Portfolio API
  version: "1.0"
paths:
  /users/create:
    post:
      consumes:
      - application/json
      description: that method creates a new user
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.CreateUserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
      summary: Create new user
      tags:
      - user
swagger: "2.0"
